config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

   resources :users

   root 'home#index'
   get '/upload', to: 'uploads#new'
   post '/upload', to: 'uploads#create'

   get '/login', to: 'sessions#new'
   post '/login' => 'sessions#create'
   get '/logout' => 'sessions#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/upload.rb
class Upload < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord

  has_many :uploads

  has_secure_password
  validates :email, :password, :password_confirmation, :presence => true

end

app/controllers/application_controller.rb
require 'uri'

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :url_host

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
    rescue ActiveRecord::RecordNotFound
  end

  def authorize
    redirect_to '/login' unless current_user
  end

  def url_host(url)
    uri = URI(url)
    uri.host
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      # Save the user id inside the browser cookie. This is how we keep the user
      # logged in when they navigate around our website.
      session[:user_id] = user.id
      redirect_to '/'
    else
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController

  def new
  end

  def create
    @upload = current_user.uploads.create(upload_params)
    if @upload.save
      redirect_to '/'
    else
      render 'new'
    end
  end

  private

  def upload_params
    params.require(:upload).permit(:scenario)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to '/'
      flash[:danger] = 'You have succesfully created your account'
    else
      render 'new'
      flash[:danger] = 'There was an error creating your account'
    end
  end

  def show
    @user = User.find(current_user.id)
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/views/home/index.html.erb
<h1>This is my Home page<h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Compliance Tool Evidence</title>
    <%= csrf_meta_tags %>


  </head>

  <body>
    <%= link_to "Home", '/' %> |
    <% if current_user %>
      Signed in as <%= link_to current_user.email, user_path(current_user.id) %> |
      <%= link_to "Logout", '/logout' %> |
      <%= link_to "New URL", upload_path %>
    <% else %>
      <%= link_to 'Login', '/login' %> | <%= link_to 'Signup', '/users/new' %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/uploads/new.html.erb
<h1>Upload URL page</h1>

<%= form_for :upload do |f| %>
  Upload: <%= f.text_field :upload_url %>
  <%= f.submit "Submit" %>
<% end %>

app/views/users/new.html.erb
<h1>Sign up page</h1>

<%= form_for @user do |f| %>
  Email: <%= f.text_field :email %>
  Password: <%= f.password_field :password %>
  Password Confirmation: <%= f.password_field :password_confirmation %>
  <%= f.submit "Submit" %>
<% end %>

app/views/users/show.html.erb
<h1 align='center'>Hey <%= @user.email %>, these are your saved items being tracked...</h1>

<% @user.uploads.each do |upload| %>
  <ul align='center' style="list-style-type: none">
    <li><%= url_host(upload.upload_url) %></li>
    <li><%=link_to upload.upload_url, upload.upload_url %></li>
  </ul>
<% end %>